### ISSUE TITLE
Task List - Long Term

### ISSUE THREAD

**Issue by CG020** [chris-machado1/csc436-project#1]
### Task List

_Here is a general list of tasks that need to get done through out the project until we reach final product - other issues will be these tasks broken down into smaller parts_

- [ ] GUI Styling --> make user navigable and well organized
- [ ] Plant Catalog --> saving option, editing options, notes and photo uploading
- [ ] Day Watering Tasks --> current day outlook, what needs to be watered or checked on
- [ ] Watering Schedule --> weekly view where watering sched is, user can add notes 
- [ ] Weather Forecast --> connect to weather API, a built in forecast that will translate to water sched to compensate
- [ ] Image Identifier --> implementation and area to save previous scans
- [ ] Other ways to get plant care tips --> brainstorm 
- [ ] Saving --> saving ones own catalog and profile, a login?
- [ ] Cross Platform --> iOS and Android compatible
